apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: golang-app
  name: golang-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
      - env:
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc:14268/api/traces?format=jaeger.thrift
        image: golang-app:latest
        imagePullPolicy: IfNotPresent
        name: golang-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
